### PR TITLE
Remove warning log when checking basalt columns

### PR DESCRIPTION
**Pull request by NattoCB**
Dear author,

https://github.com/TelepathicGrunt/RepurposedStructures/issues/329

According to the closed issue above, this log might have been deleted already, but actually as checks, it still contains within some old branches, and sometimes it will cause the log spamming and server lagging issue.

So kindly request for merging this commit into the following branches which have not deleted this log:

* 1.18-Fabric
* 1.18-Forge
* 1.18.2-Fabric
* 1.18.2-Forge
* 1.19.0-Fabric
* 1.19.0-Forge
* 1.19.0-Quilt
* 1.19.3-Fabric
* 1.19.3-Forge
* 1.19.3-Quilt

Many thanks <3

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
I am not accepting pr to unsupported Mc versions. The logging is indeed important technically as it means your pack has something messing with the basalt delta and is misplacing it. You should find who is messing it up instead of silencing the logspam. That is only hiding the problem. Not solving it

**Comment by NattoCB** [comment]
> I am not accepting pr to unsupported Mc versions. The logging is indeed important technically as it means your pack has something messing with the basalt delta and is misplacing it. You should find who is messing it up instead of silencing the logspam. That is only hiding the problem. Not solving it

Thanks for the reply, as tested it's an incompatibility issue between RS and DistantHorizens, if I remove DH and then this logs would not appear when players walking around on basalt biome

**Comment by NattoCB** [comment]
> I am not accepting pr to unsupported Mc versions. The logging is indeed important technically as it means your pack has something messing with the basalt delta and is misplacing it. You should find who is messing it up instead of silencing the logspam. That is only hiding the problem. Not solving it

or plan to decrease the logging frequency if applicable? 
because once it happens the log volume is too big and usually more than hundreds of MB or more

**Comment by TelepathicGrunt** [comment]
Figures Distinct Horizon is still causing issues in older versions. Worse still, I reeeealy do not want to release update for older versions which would give impression I still support them when I really don't and have moved on (and CurseForge will say RS is for an older version as they list the mc version of latest file)

If I do release an update, it would only be for 1.18.2 and 1.19.2. I wont do an update for dead versions like 1.19.4

**Comment by NattoCB** [comment]
ok understood... thanks for letting me know the reason behind 🤝🏻

**Pull request closed without merging**
