### PR TITLE
German (de_de) translation

### PR DESCRIPTION
**Pull request by elloellie**
i'm not a native speaker of german, but i'm minoring in it in college. me and my friends wanted to play a modpack in german to practice, so i decided to translate some mods!

anyways, this might not be 100% correct. if anything's incorrect anyone can feel free to edit it, or let me know and i'll spruce it up. i know by default you have to enable foreign language advancements with a data pack, but maybe that could change? idk!

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Awesome thank you! Though there are a few more structures that will be coming in a future update. Once I iron out all the new stuff, would you be able to translate their entries too? I'll let you know when they are done

**Comment by elloellie** [comment]
absolutely! i'd be happy to. i check curseforge's new/updated mods page obsessively so i'll probably see when you upload it :-p

**Comment by elloellie** [comment]
also i should mention, i changed some of the naming styles. in vanilla minecraft, strongholds are called "Festung", and nether fortresses are called "Netherfestung". i renamed your repurposed strongholds to labyrinths to overcome that. so now your nether strongholds are called "Netherlabyrinth"

**Comment by TelepathicGrunt** [comment]
I just pushed to the 1.16 branch the finalized translations with the new structures (mansions, 2 new mineshafts, witch huts, and 1 new temple). If you can update the german translations to have all the new entries in the new lang file on the 1.16 branch, I'll merge it in!

Here's the file if you are having trouble finding it 
[en_us.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/5985811/en_us.zip)

**Comment by elloellie** [comment]
I will get on it as soon as possible! I'm in Texas so having power and internet is a bit iffy right now lol. Still! Once things calm down I'll get to it :-)

**Comment by TelepathicGrunt** [comment]
Oof. Stay safe! Don’t rush to do the translations as they can wait until things are better for you

**Pull request merged**
