### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Updated ru_ru.json

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
@Bytegm thoughts on these translations? Since you were the last one to make the Russian translations

**Comment by mpustovoi** [comment]
The last time he was active was in January, so perhaps there won't be response from him.
I just corrected a few lines so that they better correlate with the official translation of Minecraft, and clicked 'format document', which apparently led to a 'complete' rewrite of tab characters.
The only thing I want to note is that all the ellipsis have been converted into one-character ones.

**Comment by TelepathicGrunt** [comment]
You have to change the … back to three character ones. The translation will not apply to the advancement because the advancement uses the three character version.

**Comment by TelepathicGrunt** [comment]
I'll merge and do the change manually since I am releasing an update today

**Pull request merged**
